spring:
  datasource:
    url:  jdbc:postgresql://192.168.50.10:5432/postgres
    username: root
    password: root
    driverClassName: org.postgresql.Driver
logging.level.: DEBUG
logging.level.root: DEBUG
logging.level.ROOT: DEBUG
